title: Lokesh Lakshminarayanan
description: Mathematics & CS @ BITS Pilani. Theoretical computer science, algebra, combinatorics.
author: Lokesh Lakshminarayanan
email: 1901lokesh@gmail.com
baseurl: ""
url: "https://lokesh-bitshyd22.github.io"

github_username: Lokesh-bitshyd22
linkedin_username: lokesh2005

markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules

permalink: /blog/:year/:month/:title/

collections:
  projects:
    output: true
    permalink: /projects/:name/
